### ISSUE TITLE
Add SSH support for remote backup

### ISSUE THREAD

**Issue by lorenrogers** [eaut/rsync-time-backup#6]
The script should support remote destinations using SSH.
See https://github.com/eaut/rsync-time-backup/pull/2#issuecomment-161599124 for initial discussion.

**Comment by lorenrogers** [comment]
I started up a topic branch on my fork: https://github.com/lorentrogers/rsync-time-backup/tree/ssh-support
It'll need a good amount of work before it's stable enough for a pull request into master.
It also depends on both https://github.com/eaut/rsync-time-backup/pull/10 and https://github.com/eaut/rsync-time-backup/pull/12.

I included @eaut 's suggestion for the `fn_run_cmd` function, but I've not had time to refactor all the original calls.

**Comment by eaut** [comment]
I have added a new https://github.com/eaut/rsync-time-backup/tree/ssh  branch. I have not tested the code as a whole yet. Changes so far:  https://github.com/eaut/rsync-time-backup/compare/master...ssh
Could you test the code and give me feedback?

**Comment by lorenrogers** [comment]
Overall, it seems good. But the [[ ]] statements cause issues with remotes set to use sh instead of bash or zsh. I'll see if I can get it working with my setup (which uses sh on the remote side) and give another update.

**Comment by lorenrogers** [comment]
Not sure why just yet, but `echo` doesn't seem to be evaluating properly with `fn_run`. Seems to still be running locally, even though other functions work with ssh just fine.

https://github.com/eaut/rsync-time-backup/blob/ssh/rsync_tmbackup.sh#L172

**Comment by eaut** [comment]
fixes for hopefully both problems see 384055b

**Comment by lorenrogers** [comment]
Ha - I was about to comment! I'll check that out in a bit. I think the issue is that the >> is being applied to the output of fn_run. Perhaps those changes fixed it though!

**Comment by eaut** [comment]
fixed two more in f504028

**Comment by lorenrogers** [comment]
When I run `./rsync_tmbackup.sh -v init lorentrogers@xxx.xxx.xxx.xxx:test-backup` I'm getting:

```
ssh: Could not resolve hostname : Name or service not known
ssh: Could not resolve hostname : Name or service not known
ssh: Could not resolve hostname : Name or service not known
Backup marker test-backup/backup.marker created.
```

**Comment by eaut** [comment]
latest commit should fix these problems

**Comment by lorenrogers** [comment]
I'm still having issues...

```
Unmatched '.
Illegal variable name.
Illegal variable name.
Illegal variable name.
Illegal variable name.
Illegal variable name.
chmod: test-backup/backup.marker: No such file or directory
Backup marker test-backup/backup.marker created.
```

When I add some test echos, it looks like the Unmatched part is still coming from line 176: https://github.com/eaut/rsync-time-backup/blob/ssh/rsync_tmbackup.sh#L176

I think the issue is the " characters in the text being put into the marker, combined with the parameter expansion happening as the string is passed through fn_run.

**Comment by lorenrogers** [comment]
As a sanity check, I confirmed that this command executes correctly:

```
ssh lorentrogers@xxx.xxx.xxx.xxx "echo 'test' >> 'backup.marker'"
```

In this case, it's important that the >> is within the double quotes, so that it's properly executed as part of the ssh call, rather than logging the output from it..

**Comment by eaut** [comment]
strange, it works for me. everything between two single quotes, i.e. the marker config should stay completely untouched. 
what is your destination system? have your tried it on localhost with your debian system?

**Comment by lorenrogers** [comment]
Aha! Yes, it works on localhost, but not on my nas, which runs FreeBSD. (The login shell is csh.)

**Comment by lorenrogers** [comment]
Running the script locally on the BSD machine works, so there seems to be something in the way it's passed through ssh. (That is, SSH'ing into the machine and running `./rsync_tmbackup init ./test` correctly makes the marker file.)

**Comment by lorenrogers** [comment]
I can also confirm that ssh to localhost on BSD does _not_ work.

Running;

```
./rsync_tmbackup.sh init lorentrogers@localhost:test-backup
```

Gives: 

```
[ERROR] backup location lorentrogers@localhost:test-backup does not exist
```

(It does exist though.)

**Comment by eaut** [comment]
what shell is running on your FreeBSD system when you log in via ssh?

**Comment by lorenrogers** [comment]
csh

**Comment by eaut** [comment]
multiple line quoting seems to be a known problem of csh. change your shell with "chsh".

**Comment by eaut** [comment]
ssh support merged into master

**Comment by lorenrogers** [comment]
Makes sense - I added a bit to the readme about remote shells. https://github.com/eaut/rsync-time-backup/pull/14 FreeNAS doesn't come with chsh installed, but bash and sh seem to work fine.
